### ISSUE TITLE
Game hangs on battle loading screen with soundEventInjector installed (WoT 1.16.1.0)

### ISSUE THREAD

**Issue by ClassicsWoTWorkshop** [PolyacovYury/PYmods#14]
As of today's new patch release (WoT 1.16.1.0), while running only soundEventInjector + its dependencies (using the most recent archive from Yandex), game loads as normal into hangar/etc, but upon attempting to enter any battle mode, the game hangs on the loading screen (progress bar fills up, but never finishes loading).

Scanning python.log, this caught my attention (I can provide you with the full python.log + replay file if necessary, but I did not include it here in my initial post since it is very long):

```
2022-04-12 10:47:41.531: ERROR: Traceback (most recent call last):
2022-04-12 10:47:41.531: ERROR:   File "scripts/client/Avatar.py", line 624, in onBecomePlayer
2022-04-12 10:47:41.531: ERROR:   File "scripts/client/gui/mods/mod_SoundEventInjector.py", line 255, in new_initGUI
2022-04-12 10:47:41.531: ERROR: AttributeError: 'IngameSoundNotifications' object has no attribute '_IngameSoundNotifications__events'
```

**Comment by ClassicsWoTWorkshop** [comment]
Now fixed in the version available from Yandex: https://disk.yandex.com/d/b-fqQA923Mqvwk

Thank you :)

**Comment by PolyacovYury** [comment]
I only just saw the issue report :D
Thank you for reporting, though, would be great if anything else breaks in the future :)
