### ISSUE TITLE
Bug 1.0.2 CommonTest

### ISSUE THREAD

**Issue by dkruben** [PolyacovYury/PYmods#3]
> Traceback (most recent call last):
  File "scripts/client/game.py", line 156, in init
  File "scripts/client/gui/shared/personality.py", line 371, in init
  File "scripts/client/gui/mods/__init__.py", line 19, in init
  File "scripts/client/gui/mods/__init__.py", line 67, in _findValidMODs
  File "scripts/common/Lib/importlib/__init__.py", line 37, in import_module
  File "BankLoader", line 352, in <module>
  File "BankLoader", line 36, in __init__
  File "Simple", line 24, in __init__
  File "Dummy", line 28, in __init__
  File "BankLoader", line 348, in load
  File "BankLoader", line 183, in checkConfigs
AttributeError: 'NoneType' object has no attribute 'asInt'

**Comment by dkruben** [comment]
i will test thx man
