### ISSUE TITLE
mod_radialmenu.pyc script not loading

### ISSUE THREAD

**Issue by elektrosmoker** [PolyacovYury/PYmods#5]
hello polyakov,

i have found an issue and wanted to tell you about it with sending you the log.

this is the part of the python.log that shows the error:

```
2019-05-04 15:09:10.483: INFO: ---------------------------------------------------------------------------
2019-05-04 15:09:10.486: INFO: ./mods/configs/PYmods/RadialMenu/RadialMenu.json
2019-05-04 15:09:10.486: INFO: Expecting object: line 6 column 23 (char 121)
2019-05-04 15:09:10.488: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/PYmodsCore/config/interfaces/Dummy.py", line 185, in MSAApply
  File "scripts/client/gui/mods/mod_RadialMenu.py", line 70, in onApplySettings
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 70, in onApplySettings
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 23, in <lambda>
  File "scripts/client/PYmodsCore/config/json_reader.py", line 148, in loadJson
  File "scripts/common/Lib/json/__init__.py", line 351, in loads
  File "scripts/common/Lib/json/decoder.py", line 366, in decode
  File "scripts/common/Lib/json/decoder.py", line 382, in raw_decode
ValueError: Expecting object: line 6 column 23 (char 121)

2019-05-04 15:09:10.488: INFO: [SL_PRO] Skipped Script: mod_radialmenu.pyc
2019-05-04 15:09:10.488: INFO: 
2019-05-04 15:09:10.491: ERROR: [EXCEPTION] (<string>, 596):
Traceback (most recent call last):
  File "<string>", line 584, in _findValidMODs
  File "scripts/common/Lib/importlib/__init__.py", line 37, in import_module
  File "scripts/client/gui/mods/mod_RadialMenu.py", line 267, in <module>
  File "scripts/client/gui/mods/mod_RadialMenu.py", line 35, in __init__
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 53, in __init__
  File "scripts/client/PYmodsCore/config/interfaces/Dummy.py", line 23, in __init__
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 74, in load
  File "scripts/client/PYmodsCore/config/interfaces/Dummy.py", line 113, in load
  File "scripts/client/gui/mods/mod_RadialMenu.py", line 74, in readCurrentSettings
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 65, in readCurrentSettings
  File "scripts/client/PYmodsCore/config/interfaces/Dummy.py", line 80, in updateMod
  File "scripts/client/gui/modsSettingsApi/api.py", line 133, in updateModSettings
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/PYmodsCore/config/interfaces/Dummy.py", line 185, in MSAApply
  File "scripts/client/gui/mods/mod_RadialMenu.py", line 70, in onApplySettings
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 70, in onApplySettings
  File "scripts/client/PYmodsCore/config/interfaces/Simple.py", line 23, in <lambda>
  File "scripts/client/PYmodsCore/config/json_reader.py", line 148, in loadJson
  File "scripts/common/Lib/json/__init__.py", line 351, in loads
  File "scripts/common/Lib/json/decoder.py", line 366, in decode
  File "scripts/common/Lib/json/decoder.py", line 382, in raw_decode
ValueError: Expecting object: line 6 column 23 (char 121)
```

**Comment by PolyacovYury** [comment]
```
./mods/configs/PYmods/RadialMenu/RadialMenu.json
```
Send me this file, please. It looks like it can't properly read it, I need to see why.

**Comment by elektrosmoker** [comment]
you were right! Thank you!
now i exchanged my old file with the file from your provided zip - and now it works without errors in python.log!
(btw it worked with this json file until patchday)

[RadialMenu.zip](https://github.com/PolyacovYury/PYmods/files/3146967/RadialMenu.zip)


here´s the file if you still want to take a look at it.

**Comment by PolyacovYury** [comment]
Not sure, how it could've worked.
It has closing curly bracket missing, or, rather, the whole last line.
This might've exposed an issue with my json reader/writer, so thank you for a signal.

**Comment by PolyacovYury** [comment]
Just checked. It all works completely fine.
So the only reason the file would look like that is manual editing.
